### PR TITLE
Add Babbler

### PR DESCRIPTION
**Pull request by marmistrz**

### CODE REVIEW

**Comment by jubalh** [comment]
How about "Add Babbler" instead of "Update README" ? Sure here it doesn't much but for other projects I would like to encourage you to use commit messages that are more descriptive.

**Comment by marmistrz** [comment]
Ouch, sorry, I simply forgot to change the title in this particular PR :)

**Comment by jubalh** [comment]
You changed the title of the PR but not the commit message.

**Comment by marmistrz** [comment]
Done

**Comment by bluszcz** [comment]
Thank you for the contribution!

**Pull request merged**
